on:
  push:
    branches:
      - master
  pull_request:

jobs:
  amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Set up access and checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive
      - run: ./bootstrap-seeds/POSIX/AMD64/kaem-optional-seed
      - name: Upload artifacts
        if: always() # Always upload artifacts for debugging
        uses: actions/upload-artifact@v7
        with:
          name: amd64-artifact
          path: AMD64/artifact
          if-no-files-found: error
      - name: Upload binaries
        if: always() # Always upload artifacts for debugging
        uses: actions/upload-artifact@v7
        with:
          name: amd64-bin
          path: AMD64/bin
          if-no-files-found: error

  x86:
    runs-on: ubuntu-latest
    steps:
      - name: Set up access and checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive
      - run: ./bootstrap-seeds/POSIX/x86/kaem-optional-seed
      - name: Upload artifacts
        if: always() # Always upload artifacts for debugging
        uses: actions/upload-artifact@v7
        with:
          name: x86-artifact
          path: x86/artifact
          if-no-files-found: error
      - name: Upload binaries
        if: always() # Always upload artifacts for debugging
        uses: actions/upload-artifact@v7
        with:
          name: x86-bin
          path: x86/bin
          if-no-files-found: error

  aarch64:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Set up access and checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive
      - run: ./bootstrap-seeds/POSIX/AArch64/kaem-optional-seed
      - name: Upload artifacts
        if: always() # Always upload artifacts for debugging
        uses: actions/upload-artifact@v7
        with:
          name: aarch64-artifact
          path: AArch64/artifact
          if-no-files-found: error
      - name: Upload binaries
        if: always() # Always upload artifacts for debugging
        uses: actions/upload-artifact@v7
        with:
          name: aarch64-bin
          path: AArch64/bin
          if-no-files-found: error

  # There is no full bootstrap for armv7l

  riscv64:
    runs-on: ubuntu-latest
    steps:
      - name: Install qemu and git
        run: sudo apt-get update && sudo apt-get install qemu-user

      - name: Set up access and checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - run: qemu-riscv64 ./bootstrap-seeds/POSIX/riscv64/kaem-optional-seed
      - name: Upload artifacts
        if: always() # Always upload artifacts for debugging
        uses: actions/upload-artifact@v7
        with:
          name: riscv64-artifact
          path: riscv64/artifact
          if-no-files-found: error
      - name: Upload binaries
        if: always() # Always upload artifacts for debugging
        uses: actions/upload-artifact@v7
        with:
          name: riscv64-bin
          path: riscv64/bin
          if-no-files-found: error

  riscv32:
    runs-on: ubuntu-latest
    steps:
      - name: Install qemu and git
        run: sudo apt-get update && sudo apt-get install qemu-user

      - name: Set up access and checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - run: qemu-riscv32 ./bootstrap-seeds/POSIX/riscv32/kaem-optional-seed
      - name: Upload artifacts
        if: always() # Always upload artifacts for debugging
        uses: actions/upload-artifact@v7
        with:
          name: riscv32-artifact
          path: riscv32/artifact
          if-no-files-found: error
      - name: Upload binaries
        if: always() # Always upload artifacts for debugging
        uses: actions/upload-artifact@v7
        with:
          name: riscv32-bin
          path: riscv32/bin
          if-no-files-found: error

